### ISSUE TITLE
Address AthenaDirect table_whitelist features

### ISSUE THREAD

**Issue by alison985** [mozilla/redash#103]
Right now the AthenaDirect data source for query_runner contains functionality around a table_whitelist that is not present in the Athena data source type. Determine if this needs to be added upstream, added to the mozilla fork, or something else.

**Comment by rafrombrc** [comment]
This was because certain tables didn't work with AthenaDirect, so rather than have them show up and be broken we set things up so we'd have to explicitly mark tables as working. We'll need to investigate with the new Athena query runner to see if the issues we had with AthenaDirect have been resolved; if not, we'll need to re-add this feature. @robotblake should be able to help inform you of what the issues were, and help test.

**Comment by alison985** [comment]
Investigation pending M6 release on 7/24.

**Comment by alison985** [comment]
I spoke with @robotblake today and he said that pre-M6 release to prod that prod was running the old proxy query runner for Athena, and therefore didn't have the whitelist functionality. Prod now appears to be running the upstream PyAthena version of the query runner. Leaving this ticket open to monitor.
