### ISSUE TITLE
Dashboards with templates behave strangely when refreshed

### ISSUE THREAD

**Issue by emtwo** [mozilla/redash#164]
### Steps to Reproduce

1. Go to https://sql.telemetry.mozilla.org/dashboard/test_9
2. Refresh the page.

Expected result: The URL should remain the same and nothing should change
Actual result: The URL changes to: https://sql.telemetry.mozilla.org/dashboard/test_9?p_start_date=05%2F15%2F17&p_end_date=06%2F18%2F17&p_experiment_id=exp-20-topsites-tworows&p_addon_versions=(%271.11.0%27,%20%271.12.0%27,%20%271.12.1%27,%20%271.13.0%27)&p_events_table=activity_stream_events_daily&p_event=(%27SEARCH%27) and it sets the `event` variable to `SEARCH` for all graphs.

**Comment by alison985** [comment]
@emtwo when I click the link to the test_9 dashboard it gives me the long url version immediately without a refresh. I've never played with a dashboard that has variables before, so I am going to research more about their expected behaviors.

I can reproduce the `event` variable change and have marked that as a bug for the next sprint.

**Comment by emtwo** [comment]
Thank you @alison985!

**Comment by alison985** [comment]
@emtwo, this is happening because the `event` variable is the same name in both queries on the dashboard. If you changed one to be named meep_event and one to be named beep_event, for instance, then they would be unique and could maintain different values.

Example:

https://sql.telemetry.mozilla.org/dashboard/alison-test-for-164
https://sql.telemetry.mozilla.org/dashboard/alison-test-for-164?%3Fp_start_date=05%2F15%2F17&p_end_date=06%2F18%2F17&p_experiment_id=exp-20-topsites-tworows&p_addon_versions=(%271.11.0%27,%20%271.12.0%27,%20%271.12.1%27,%20%271.13.0%27)&p_events_table=activity_stream_events_daily&p_event=(%27SEARCH%27)&p_beep_event=(%27CLICK%27)&p_meep_event=(%27SEARCH%27)&p_start_date=5%2F18%2F2017

Also, another note for me is that once you have a parameter name in the query you don't seem to be able to remove it. Right now I have event and meep_event/beep_event in my example.

**Comment by alison985** [comment]
Turns out, parameter names are removable in the manner I would expect so there is no bug on that score. 

@emtwo, could you weigh in on whether giving variables unique names is an acceptable solve for you?

**Comment by alison985** [comment]
@emtwo does each unique parameter on a dashboard having a unique name work for you?

**Comment by emtwo** [comment]
@alison985 sorry for the late response. I could make it work with having unique parameter names, but it would not be ideal for me. The way I currently use templates is by forking a template multiple times and injecting each fork with a different set of values for its parameters.

So I'd have to do an additional step after forking of changing the variable names so they are not repeated.

I think in that case this issue may not be a high priority but it would definitely be a "nice to have"

**Comment by alison985** [comment]
@arikfr I intend to work on this tomorrow. My plan is to add the widget id to the parameter name so each widget can have unique parameter names. This is going to involve touching a lot of places in the code, so I wanted to touchbase with you if you possible to get any thoughts you have so that we can send this upstream.
