### ISSUE TITLE
Public URL for a dashboard that contains a text widget throws 500 server error

### ISSUE THREAD

**Issue by madalincm** [mozilla/redash#220]
### Issue Summary:

Build identifier: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:55.0) Gecko/20100101 Firefox/55.0

### Steps to Reproduce:
1. Open a dashboard that contains a text widget.
2. Generate a public url and try to open that url.

### Expected results:
The url can be loaded, the dashboard is displayed.

### Actual results:
500 Error displayed in the console, the dashboard can't be accessed.

### Notes/Issues:
Verified in FF55(Win7).  Issue can be reproduced only in STMO stage and STMO prod

Example of a dashboard that contains a text widget: https://pipeline-sql.stage.mozaws.net/dashboard/textwidgetservererrorinpublicurl

Public URL that returns the server error: https://pipeline-sql.stage.mozaws.net/public/dashboards/fOO9BUW3svpUGgbqI59Honzgv5XjfufvsTllhqma?org_slug=default

**Comment by washort** [comment]
Looks lik this is a result of the changes for #166: https://sentry.prod.mozaws.net/operations/data-stmo-stage/issues/642969/events/11758337/

**Comment by madalincm** [comment]
Verified fixed in FF55(Win7) in stmo-stage.

**Comment by washort** [comment]
We are dropping this fix from m21 because `run_query_sync` has been removed upstream. We believe this will have low impact because queries with no results are run when added to a dashboard, meaning that this error will only occur until the query completes. The long term solution is probably the one in https://github.com/getredash/redash/issues/2844 .

**Comment by jezdez** [comment]
Closing as this has not been requested again.
