### ISSUE TITLE
Allow refresh schedule to be set for an entire dashboard

### ISSUE THREAD

**Issue by emtwo** [mozilla/redash#24]
This would be handy so you don't have to individually set each graph's refresh schedule

**Comment by rafrombrc** [comment]
Unfortunately, this one is a bit more complicated than it seems. A single query can have more than one visualization, and a single visualization can be used in more than one dashboard. What happens if someone uses the same visualization in two dashboards that each have a separate refresh schedule? The naive result would be for whichever dashboard was edited last to change the query's refresh schedule, but that's clearly not what we want. There may be ways around this, but it also may not be worth the effort. Open to ideas.

**Comment by emtwo** [comment]
I'm personally in less need of this as I've been using the API to quickly/easily set refresh schedules. If it's not something requested by others and it's not worth the effort perhaps we can close this.

**Comment by rafrombrc** [comment]
Awesome, thanks. Closing, we can open a new issue if the need comes up again.
