### ISSUE TITLE
Pie Chart visualization not displayed for some queries

### ISSUE THREAD

**Issue by madalincm** [mozilla/redash#248]
### Issue Summary:

Build identifier: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:55.0) Gecko/20100101 Firefox/55.0

### Steps to Reproduce:
1. Open this query https://pipeline-sql.stage.mozaws.net/queries/131/source#165
2. Observe the missing pie chart.

### Expected results:
The pie chart is displayed

### Actual results:
The pie chart is not displayed

### Notes/Issues:
Verified in FF55(Win7).  
Screencast for this issue:
![piechartnotworking](https://user-images.githubusercontent.com/15685441/30032127-c9de16a2-919c-11e7-80fa-5a4abfc43168.png)

**Comment by alison985** [comment]
@madalincm Here's a brand new query (just made just now) that works: https://pipeline-sql.stage.mozaws.net/queries/132/source#170 and here's your query with a more reasonable limit : https://pipeline-sql.stage.mozaws.net/queries/133/source#172 

Your particular query works fine if you lower the limit to say 10 instead of 100. Unlike what I first thought, which was that the JS of the query just ended up in a bad state and the need to make a new query. I think the issue is it doesn't know how to display 100/1 (since in your query returns 100 rows with a count of one each). I think it's reasonable for it not to know how to display 100 pie slices.

I'm going to mark this as won'tfix.
