### ISSUE TITLE
[Feature request] Sort redash search queries by headings, e.g. "Update schedule"

### ISSUE THREAD

**Issue by mcomella** [mozilla/redash#262]
### Issue Summary
I'm searching for specific information (engagement with Android top sites pre-Activity Stream in [bug 1377288](https://bugzilla.mozilla.org/show_bug.cgi?id=1377288)) and going through the list of query results for "android". There are ten pages of results. It'd be great to sort by, "Update schedule" to find the queries that are run regularly, which means the ones that people are more likely to be using and keeping up to date, and thus probably the most useful to me.

In general, this means it'd be great to sort by the headers in a search query, such as "Update schedule".

**Comment by madalincm** [comment]
Verified in FF57(Win7) in stmo-stage
The ability to order the queries returned by a search is implemented but does not seem to, completely, work. For example sorting by Update Schedule is not ordering the queries correctly, or sorting  by Created by does not sort the queries alphabetically. The sort by Name and Created at works correctly.

I'm marking this bug as verified fixed since this will not break anything in production and will add some functionality. I will add some follow up issues so we track the ordering by updated schedule and created by fields.

**Comment by madalincm** [comment]
Follow-up issues: #303  #304
