### ISSUE TITLE
re:dash PyHive version should include pretty printing of structs

### ISSUE THREAD

**Issue by fbertsch** [mozilla/redash#264]
Awhile ago we were using a fork of PyHive (at vitillo/PyHive). Which included the following PR: https://github.com/dropbox/PyHive/pull/82

It seems that when I pushed the query cancellation changes upstream, we also merged the updated PyHive version, which means we stopped using the one with pretty printing of structs. We need to:

1. Create a mozilla fork of PyHive, and point mozilla/redash there
2. Merge the pretty printing PR
3. Remove [this line from PyHive](https://github.com/dropbox/PyHive/blob/master/pyhive/presto.py#L282), which only serves to prevent us from seeing errors

**Comment by alison985** [comment]
@fbertsch Are we sure we want a Mozilla fork instead of going back to using the vitillo/PyHive fork? This is really more a question to help me understand and edify me than anything else.

**Comment by fbertsch** [comment]
@alison985 yes, because I don't think vitillo will be keeping that version up-to-date with upstream/master.

**Comment by alison985** [comment]
@jasonthomas @robotblake Could you please help me in creating a fork of PyHive within the Mozilla organization on Github?

**Comment by jasonthomas** [comment]
I've forked PyHive https://github.com/mozilla/PyHive and given the DataTools team and you access to this repo.

**Comment by jezdez** [comment]
Hey all, I strongly disagree that we should fork the whole library if we only want to do some data post-processing.

@alison985 The redash code uses the `pyhive.presto.connect` [function here](https://github.com/vitillo/PyHive/blob/0fce4d8b113b0e843f1d045534a76c7fda656586/pyhive/presto.py#L41) which just instantiates a `Connection` object.

We can easily port the `_pretty_` method to a subclass of `pyhive.presto.Connection` (e.g. `PrettyConnection`) which does what we need.

To cater to point 3 of @fbertsch's list above we can override `_process_response` as well, call the parent `_process_response` but catch `DatabaseError` and reraise it to never miss it again.

As I understand it this would give us what @fbertsch needs without the tech debt of yet another forked dependency.

@jasonthomas Do you concur?

**Comment by jasonthomas** [comment]
I am okay with this approach. I will remove the fork.

**Comment by alison985** [comment]
Hi @fbertsch and @jezdez, pinging again on this one.

**Comment by jezdez** [comment]
@alison985 Sorry I missed this comment, this looks good in general but I dislike that we have to copy the whole method and think it could prevent merging it upstream. Sadly we can't just override the `_decode_binary` method to apply `_pretty` since it doesn't pass back the `new_data`. Could we actually make a patch against PyHive and add a new method there to support our use case? I know it's a bit of yak shaving, but it pays off long-term.

**Comment by alison985** [comment]
@jezdez The original PR against dropbox/PyHive was rejected because it's a breaking change. The comment included: "If I'm reading this code correctly, the only edit it does is to attach column names to struct type fields. That's an incompatible change from a list to a dict, so could you do the transformations on your end of the code instead? (e.g. via a wrapper or subclass)"

**Comment by fbertsch** [comment]
@jezdez It's been hard to communicate with the PyHive owners, and there have been long periods of silence - so I'm not sure it's worth coming up with some sort of acceptable API with them. Your solution was our original solution.

IMO, this change is important enough to warrant a bit of ugliness. It is a huge usability improvement for our end users.

**Comment by fbertsch** [comment]
Can we come up with a short-term and long-term solution here? Short-term, this fix in our re:dash fork. Long-term, we open an issue to come up with an API for this change in PyHive, and once they've agreed on what the change will look like we open a PR. Once that merges we remove this code?

cc @alison985 @jezdez

**Comment by jezdez** [comment]
@alison985 Ah, thanks for the reference, in that case we'll have to live with the length of the method. Let's open a PR upstream and see if the other Redash devs are against it.

@fbertsch Yeah, this is a area where we strive to have the best of both worlds, a quick solution and also not make things hard to maintain on the long run. We've worked hard to get a foot in the door in the Redash upstream project so we don't have to solve problems like this in our fork (read: accruing technical debt) so I'm convinced that direction is preferrable.

So let's first see how the feedback from the other Redash devs turns out and we can always decide to try to solve this in our redash-stmo extension (via monkeypatching) instead (which we can iterate quickly) or whatever works.

**Comment by alison985** [comment]
PR upstream https://github.com/getredash/redash/pull/2696

**Comment by alison985** [comment]
@washort This fails upstream on circleci test errors: https://circleci.com/gh/getredash/redash/4447?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link but it a) doesn't find any tests but reports 42 errors, and b) all 477 tests pass locally. Any ideas?

**Comment by rafrombrc** [comment]
We've decided to retract this upstream PR and move this functionality into an extension for Mozilla's use. @jezdez will tackle porting this into the extension code.

**Comment by jezdez** [comment]
I've opened https://github.com/mozilla/redash-stmo/pull/19 to have an own Presto query runner there.

**Comment by jezdez** [comment]
Merged into redash-stmo and deployed in the recent deploy. @fbertsch Care to double-check if things are as exptected?
