### ISSUE TITLE
html tags no longer work in query results

### ISSUE THREAD

**Issue by kewisch** [mozilla/redash#269]
sql.t.m.o used to allow `CONCAT("<a href='", field1, "'>", field2, "</a>")` and render the link, which seems to not work any more. I couldn't find any specific docs on how this changed in the latest redash, so I am not sure if this was removed or if I just need to do something differently. It was definitely useful to make results a bit more compact than just returning the full url.

Can we make this come back?

**Comment by kewisch** [comment]
Extending this to various html tags. The `<div> example in https://redash.io/help/query-examples-hacks/redash-hacks.html does no work either.

**Comment by kewisch** [comment]
Just checked with the redash folks, this still works upstream so it must be something with our fork.

**Comment by washort** [comment]
This is a result of fixing https://github.com/mozilla/redash/issues/222 -- it's not clear that we should put text fields from data sources directly into the page unescaped.

**Comment by kewisch** [comment]
I see how this may be an issue, there are also potential security issues here if the data is from a public source. Is there a way this can be explicitly enabled, maybe using a similar construct as `::filter`, e.g. `SELECT CONCAT("<a href='", field1, "'>", field2, "</a>") as name::html`

**Comment by arikfr** [comment]
Note that in upstream's v4 (current master, still WIP), we added configuration for the table visualization and you can now enable/disable HTML rendering of a column.

**Comment by kewisch** [comment]
That would do it for me. Do you have a release schedule for v4, and maybe also how long after it may be deployed on stmo? (Ballpark is enough)

**Comment by washort** [comment]
Our next deployment should incorporate this change.

**Comment by arikfr** [comment]
Just note that currently master includes some changes that will need some more iterations until I consider them ready:

* New dashboard layout engine. I believe we will do another iteration there to figure out the initial size widgets get and the size "steps" we use.
* Schema browser currently disappear only when not supported, but there is an empty space instead of expanding the query editor.
* The new design will probably go another iteration or two until we consider it done.

**Comment by rafrombrc** [comment]
We *might* be able to do a deployment next week, but it's a risky time to make changes since we don't want to break things right before going away for the holidays, so it might not happen until January.

**Comment by rafrombrc** [comment]
Oops, turns out that while this *has* been fixed upstream, it comes along with some sizable UI changes that will need a significant amount of review before we feel comfortable deploying it to production. In other words, this will not be in the next deployment, but it will be coming soon, hopefully within the next 3-4 weeks.

**Comment by madalincm** [comment]
I'm not sure how we can test this in stage. @washort any thoughts?

**Comment by washort** [comment]
the 'Edit' dialog for tables lets you enable HTML content for columns. See this query for an example: https://pipeline-sql.stage.mozaws.net/queries/276/source

**Comment by madalincm** [comment]
Thanks for the example, unfortunate stage is down again I have reopened #307

**Comment by madalincm** [comment]
Verified as fixed in FF58(Win7) in stmo-stage
Html tags are now working. Here are some examples: https://pipeline-sql.stage.mozaws.net/queries/342/source
https://pipeline-sql.stage.mozaws.net/queries/341/source
https://pipeline-sql.stage.mozaws.net/queries/276/source

Marking bug as verified fixed.
