### ISSUE TITLE
Inconsistent time formats

### ISSUE THREAD

**Issue by madalincm** [mozilla/redash#441]
### Issue Description
1. Open this page: https://data-stmo-rc.stage.mozaws.net/users and observe the last active data format.
2. Open this page: https://data-stmo-rc.stage.mozaws.net/admin/queries/tasks#done and observe the created at data format.

-- 2 different time formats are displayed. In the first case we have UTC time (2018-06-25T08:51:11+00:00 - at the time this issue was logged) and in the second place I got my local time (2018-06-25 11:51 - at the time the issue was logged)

Is there a reason why we use different time formats in different places? I think sticking with the current local time everywhere should be the right call.

**Comment by jezdez** [comment]
The user list was refactored upstream in https://github.com/getredash/redash/pull/2715 to use human a readable format and match the other list views.

The admin status view uses a different format since it's relating to information about the infrastructure which may be more useful to copy a date/time for further investigation by operations staff. 

I'm closing this since I think the move to human readable format in the user list solved the glaring issue of using the old ISO formatting in UTC. Please open this issue upstream in case you think that's not a good idea, and include the UX people for further discussion.
