### ISSUE TITLE
Port re-prompt for login if an unauthorized Google account is used

### ISSUE THREAD

**Issue by jezdez** [mozilla/redash#457]
Refs #79 (59366660e2c67686c545480c69f341e9cacb633f)

Upstream issue: https://github.com/getredash/redash/issues/1924
Upstream PRs: ~~https://github.com/getredash/redash/pull/1897~~, https://github.com/getredash/redash/pull/2203

We've stopped using Google auth for STMO, so getting rid of this would be great.

**Comment by alison985** [comment]
@jezdez I'm uncertain about how to adjust the code to respond to Arik's feedback here: https://github.com/getredash/redash/pull/1897/files#r138621361 

> Instead of relying on a session variable, let's pass a query string option to the redash.login route, which will tell it to ask the user to pick a new account (I guess this is what extra['prompt'] = 'consent' does).

Because this is about google app authentication it is hard to test locally.

Here's Allen's commit minus code Arik says breaks multiple google org support: https://github.com/StantonVentures/redash/commit/d75c3f95f6c7078e3dc3282bc3038868786d150f It passes the test suite.

Then here is the next commit with my attempt at passing a query string instead of a session variable: https://github.com/StantonVentures/redash/commit/5024c7f4fcc53e505755cc52b4594700b06566c7 Test suite passes.

Could you please review before I close https://github.com/getredash/redash/pull/1897 and open a new PR upstream?

**Comment by jezdez** [comment]
@alison985 I've left a few commons in the original PR under Arik's review comments. I do think we'll need to add a new optional Redash setting for the hd parameter since I don't see another way to select one.

**Comment by alison985** [comment]
@jezdez I'm a unclear about the hd parameter.

**Comment by alison985** [comment]
https://developers.google.com/identity/protocols/OpenIDConnect#authenticationuriparameters  REDASH_GOOGLE_AUTH_HOSTED_DOMAIN

**Comment by alison985** [comment]
PR upstream link: https://github.com/getredash/redash/pull/2801

**Comment by jezdez** [comment]
Closing as wontfix since we believe this has been made moot by a) upstream changes with which the login page is shown even if Google is used alone as the auth provider b) we're not using Google auth anymore.
