### ISSUE TITLE
STMO RC is down

### ISSUE THREAD

**Issue by madalincm** [mozilla/redash#462]
### Steps to reproduce
1. Open  https://data-stmo-rc.stage.mozaws.net/

### Expected Results:
Page loads

### Actual Results:
Server error

### Notes/Issues:
Verified in FF61(Win7)
Issue can be reproduced in STMO-RC

**Comment by jezdez** [comment]
Up for me. @jasonthomas Any details what the cause of the downtime was?

**Comment by jasonthomas** [comment]
I do see some unusual tracebacks related to connectivity to RDS - https://sentry.prod.mozaws.net/operations/data-stmo-rc/issues/4470328/

**Comment by madalincm** [comment]
Is working for me too now

**Comment by jezdez** [comment]
@jasonthomas Huh, odd. I don't recall seeing similar things for stage or prod. Is this something that could be a result of differences in the RDS setup for rc?

**Comment by jasonthomas** [comment]
The RDS setup for RC is similar to stage, as in they are the same instance types. I tried looking into RC RDS, EC2 (both web and worker node) logs and I can't seem to find anything useful. A quick search for this error shows that it might be memory related but I am not seeing us hit any memory constraints on these instances so far. 

Looking more into sentry this IntegrityError occurred https://sentry.prod.mozaws.net/operations/data-stmo-rc/issues/4461808/ first which seems may have caused all operations to block until it was rolled back.

**Comment by jezdez** [comment]
@jasonthomas For the record, this seems like something of a red herring since it happens after a non-sense query was executed to store the results. I think this basically left the database in an unhealthy state and the immediate INSERT to add the result of the failed query triggered this exception. I would argue that the behavior in question was correct that it raised an exception, but I'm not sure why SQLAlchemy threw its hands up afterwards and declined to continue to work. Maybe the rollback just took longer than expected?

**Comment by jasonthomas** [comment]
I agree I think the rollback took longer than expected. This might be fine for a non-production environment. We could potentially improve rds performance by increasing the rds instance size but not sure if it is necessary.

**Comment by jezdez** [comment]
Okay, that makes sense, let's keep an eye on this and follow-up if it shows up again. Thanks for your help, @jasonthomas!
