### ISSUE TITLE
Investigate porting hide query more menu if empty

### ISSUE THREAD

**Issue by jezdez** [mozilla/redash#554]
#208, PR: #209

We need to check if this is applicable to upstream since there may be other modifications to the menu in our fork requiring it.

**Comment by alison985** [comment]
This is no longer a necessary diff between upstream and our fork because the UI has changed. In upstream master this menu is no longer displayed at all before save - which is what this change does.

There is a difference in the menus - on our fork there is an extra option to "Manage Permissions" but it only displays after a query is saved so it has no application to this use case. 

Closing ticket.
