### ISSUE TITLE
Chart display issue for some queries

### ISSUE THREAD

**Issue by madalincm** [mozilla/redash#57]
### Issue Summary:

Build identifier: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:52.0) Gecko/20100101 Firefox/52.0
Window 7 64 Bit

### Steps to Reproduce:
1. Open the following query: https://sql.telemetry.mozilla.org/queries/2054#3731
2. Hover over the chart and observe the value displayed for the 3rd and the 4th bars

### Expected results:
The size of the bar is proportional with its value.

### Actual results:
The bar having a value of 14.301k  is having the same size as the one with value of 1.

### Notes/Issues:
Verified in FF52(Win7).  Issue can be reproduced in STMO-production.
Screencast for this issue:
![querychartdisplayissue](https://cloud.githubusercontent.com/assets/15685441/24156833/5aa6a0fc-0e60-11e7-9e3d-1bc6c85844f8.gif)

**Comment by alison985** [comment]
Here's a fork showing the chart if they did a groupby and stacked it: https://sql.telemetry.mozilla.org/queries/4880/source#9978

The issue here is there are 3 column and it seems to be auto-grouping by the x-axis field and not recognizing the version distinction by default.

**Comment by alison985** [comment]
On my local test case, it should look like:
![Screenshot 2017-06-20 12.25.48.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57b2c9f2e8b24c1300b4dd77/125516c66e82c728ace21e0d46db978826878dba87e6ab03f60da1c36416713e7b54e37a22cbb17df1162343434d0eee1e020a17b8eb8339a3be3b798d085ded80385d75c46810feb88249b600bd26df5d99a4fedb1294b7607caddecd5d340c071e83fe593ca7904cc050f24ae94b52b65e.png)
but when I remove the groupby column it looks like this:
![Screenshot 2017-06-20 12.27.08.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57b2c9f2e8b24c1300b4dd77/125516c66e82c728ace21e0d46db978826878dba87e6ab03f60da1c36416713e7b54e37a22cbb17ff1122343434d0eee1e020a17b8eb8339a3be3b798d085ded80385d75c46810feb88249b600bd26df5d99a4fedb1294b7607caddecd5d340c071e83fe593ca7904cc050fe4fe14e57b65e.png)
Notice that the "query" column is shorter in the second picture, because unlike the production test case it is only grabbing 1 of the multiple values for query in the underlying table instead of grouping them. However, this is also an error because it falsely misrepresents the action_count of "query" as too low by discarding records.

There are a couple of paths to resolution as I see it:
1) a) allow for multiple columns to be selected into the X axis form field so distinctions are made and more columns show up on the graph to represent all result rows and b) if there are more than 2 dimensions in a query auto-add the non-used dimensions to an "ignore column" form field/configuration value.
2)  Default stacking to enabled so people have to opt-out of seeing the distinctions should this case occur. (User error prone.)
3) Start showing the user warnings on graph configurations that don't make sense. For instance: related to #58 {pseudocode} if x-axis label height > 50 then show warning to edit x-axis height field {/pseudocode}, related to this ticket: {pseudocode} if 2 or more dimensions then show warning to alter query to 2 columns or add group by and enable stacking {/pseudocode}
4) Figure out a way to stop the x-axis labels from being limited to occurring in the list of values only once.
5) something else I haven't thought of yet

The argument for option #3 in my opinion is:
i) Teaches users more about the chart edit options available to them as a side effect while correcting for the issue.
ii) The code should be much easier/faster to write because it's "detect this and display a warning" as opposed to "find this case and handle it and its related cases gracefully". Also reduces the possibility of finding future unaccounted for edge case bugs.
iii) Sets a foundation for giving additional warnings and best practice information on charts to users in the future. (i.e. "You probably really don't want a pie chart.", etc.)

**Comment by alison985** [comment]
Error and warnings for this ticket implemented in PR #91. I left the issue from #58 alone because it's way harder.
