### ISSUE TITLE
KeyError: 'version' - Unable to parse data source version for mysql: 'version'

### ISSUE THREAD

**Issue by jasonthomas** [mozilla/redash#749]
https://sentry.prod.mozaws.net/operations/data-stmo-prod/issues/5059048/

I am seeing this specifically for the 'Treeherder' datasource in our production installation.

```
KeyError: 'version'
  File "redash_stmo/data_sources/version/__init__.py", line 53, in get_data_source_version
    version = json.loads(data)['rows'][0]['version']

Unable to parse data source version for mysql: 'version'
```

**Comment by emtwo** [comment]
FWIW this is fairly harmless, it just means that users won't be able to see the data source version for mysql data sources.

The reason is that here: https://github.com/mozilla/redash-stmo/blob/master/src/redash_stmo/data_sources/version/__init__.py#L53 the assumption is that Redash creates a column with the name `version` to store the queried version data. However, when this query runs in mysql, the column name is `version()`. The simple fix here is to label the column when running the query: `select version() as version`

**Comment by jezdez** [comment]
Ooops, missed this ticket and opened https://github.com/mozilla/redash-stmo/issues/15 as well.

**Comment by jezdez** [comment]
@emtwo Thank you for figuring this out, I opened https://github.com/mozilla/redash-stmo/pull/16 with that fix.

**Comment by jezdez** [comment]
This should be fixed the next time we upgrade redash-stmo. Leaving the ticket open until then.

**Comment by jezdez** [comment]
@rafrombrc What is this blocked by?

**Comment by jezdez** [comment]
Uh, I think the datasource version isn't shown at all right now. @emtwo I'm trying to understand what's going on, do you have a lead on this?

**Comment by jezdez** [comment]
This should have been fixed now.
