### ISSUE TITLE
Visible UI element to report a mozilla Redash issue

### ISSUE THREAD

**Issue by georgf** [mozilla/redash#803]
From chat conversations i see, it is not immediately clear to our Mozilla users where they should go to file issues.

Does it make sense to add a UI element somewhere in our install that allows them to find this repository/issues or [the right bugzilla component](https://bugzilla.mozilla.org/enter_bug.cgi?product=Data%20Platform%20and%20Tools&component=Redash%20(STMO))?

**Comment by jezdez** [comment]
Yeah, having a link somewhere would make sense.

But adding a completely new UI element is not as easy as it sounds (read: easily maintainable) since Redash is an off-the-shelf product that we've been maintaining as a fork to support our customizations, but with tremendous cost involved.

We're in the process of [porting our customizations](https://github.com/mozilla/redash/projects/3) to the [upstream repo](https://github.com/getredash/redash) or our Redash extension [redash-stmo](https://github.com/mozilla/redash-stmo) to reduce that effort.

So this customization would have to be done in our Redash extension and not here. I've opened https://github.com/mozilla/redash-stmo/issues/18 to track this new feature.

Thanks for raising this issue!
