### ISSUE TITLE
Internal Server Error sending data to query_results endpoint

### ISSUE THREAD

**Issue by kewisch** [mozilla/redash#908]
### Issue Summary

I'm sending queries programtically to https://sql.telemetry.mozilla.org/api/query_results using https://github.com/teppeis/redash-client . I get an internal server error on a request that used to work.

### Steps to Reproduce

I've reduced the test case to this:

`curl -XPOST -H "Content-Type: application/json" -d '{ "query": "SELECT 1", "data_source_id": 25, "max_age": 0 }' -H "Authorization: Key YOUR_API_KEY_HERE" -H "agent: commandline" https://sql.telemetry.mozilla.org/api/query_results`

The result is a 500 response with `{"message": "Internal Server Error"}` in the body.

**Comment by jezdez** [comment]
@kewisch I've found two 400 errors which were created with curl with the result `Expecting property name enclosed in double quotes: line 1 column 24 (char 23)`. This was just the debugging call?

**Comment by jezdez** [comment]
Okay, found a few more of those calls, which seem to me like debugging calls only.

But I also found the actually larger issue when not being done via curl but via the redash-client library, which triggers a known issue with Celery that we're investigating at the moment anyways: #766

@jasonthomas @washort I think we need to shift our focus to this issue more since this issue @kewisch seems simply be a manifestation of the Celery worker not being able to properly handle query error behind the scenes. Since the /api/query_results API will actually run the queries if there is no cache, it means we're seeing it there as well as when running queries with the schedule.

**Comment by kewisch** [comment]
Yes, the 400's were me doing it wrong. I did at least one request afterwards though that reproduced the error. A simple `SELECT 1` query seems to be ok though, but I guess there is some other error behind the scenes?

**Comment by jezdez** [comment]
Yeah, the 400 errors are just red herrings, the real issue is basically #766 in disguise. Why there are many more database errors that trigger #766 is something we should probably have @jasonthomas look into.

@kewisch FTR technically we don't support 3rd party clients like this, so while it may have worked in the past, this will need some time to investigate as it's outside of our usual areas of expertise.

**Comment by jezdez** [comment]
@kewisch We've deployed a fix for #766 upstream and deployed it to prod, would you mind trying your code again?

**Comment by kewisch** [comment]
This seems to work now, thanks for following up!
