### ISSUE TITLE
CreatedBy field missing in alerts page

### ISSUE THREAD

**Issue by madalincm** [mozilla/redash#925]
### Steps to Reproduce:
- Open https://data-stmo-rc.stage.mozaws.net/alerts
- Observe the header of table where the created alerts are displayed

### Expected results:
The header contains Created by field with the author of the alert

### Actual results:
The Created by field is missing

### Notes/Issues:
Verified in FF66(Win7).  Issue can be reproduced only in STMO-RC
Please view this screenshot: 
![Screenshot_2019-03-28 Alerts](https://user-images.githubusercontent.com/1610/55144615-848bf680-5141-11e9-8a47-b9556ca06b5e.png)

**Comment by jezdez** [comment]
That was changed upstream in favor of just showing the user's avatar instead of an own column, https://github.com/getredash/redash/commit/194f45263b5a56205045becd17ef3682143ed788#diff-b598d4f9648bddee1c771744263cb7e4

I'm fairly certain that we won't be able to extend this user interface, but it's definitely a change in behavior. @madalincm Okay if I close this as works-as-expected?

**Comment by madalincm** [comment]
We have 4 sort buttons but only 3 fields to sort by and the first sort button seems to be related to the Created by field.  Maybe we can remove that first sort button?
