### ISSUE TITLE
More Info tooltip not displayed for Athena 

### ISSUE THREAD

**Issue by madalincm** [mozilla/redash#939]
### Steps to Reproduce
1. Open create a new query page and select Athena Data source
2. Hover one of the tables

### Expected results:
The more info tooltip is displayed

### Actual results:
No tooltip

### Notes/Issue
Verified in FF66 win7x64 Issue can be reproduced in STMO-RC 
Please view this screenshot: 
![moreInfoTooltipAthena](https://user-images.githubusercontent.com/15685441/55961150-e9356e00-5c76-11e9-9f65-6ddfc2c2381d.png)

**Comment by emtwo** [comment]
I believe that most tables do not show the tooltip since this data source originally had the `column_metadata`field set to false because athena's glue processing did not include it. Now that glue does include it, this field needs to be updated in the database.

Alternatively, removing and re-adding this data source should resolve the issue. Though this needs to be fixed since it will come up for other data sources that later have metadata added to them.

**Comment by madalincm** [comment]
Verified as fixed in STMO-RC. The tooltip is now displayed.
