### ISSUE TITLE
Documentation links not displayed

### ISSUE THREAD

**Issue by madalincm** [mozilla/redash#955]
### Steps to reproduce:
1. Open the new query page: https://data-stmo-rc.stage.mozaws.net/queries/new
2. Observe the UI elements displayed in the page

### Expected results:
The link for the docs is displayed.

### Actual results:
The link is not displayed.

### Notes
Verified in FF66 win7x64 Issue can be reproduced in STMO-RC

**Comment by madalincm** [comment]
There still are some data source that do not have documentation links:
- Athena
- Athena prod
- Presto

**Comment by emtwo** [comment]
For Athena and Athena Prod, this is expected behaviour since we don't have a data source link associated with Athena in the extension: https://github.com/mozilla/redash-stmo/blob/master/redash_stmo/data_sources/link/__init__.py#L9.

I've filed a separate issue for that there: https://github.com/mozilla/redash-stmo/issues/36

For Presto, the documentation link just wasn't set in the admin. I've set it and it seems to be visible now.

**Comment by jezdez** [comment]
This works as expected, some data sources need that info only.

**Comment by madalincm** [comment]
Not reproducing anymore - link for Presto is displaued. Tried on Win7x64 and MacOS 10.14.1 FF68 on dev stage and prod.
