### ISSUE TITLE
Unnecessary UI element displayed next to the Execute button

### ISSUE THREAD

**Issue by madalincm** [mozilla/redash#962]
### Steps to reproduce:
1. Open the new query page: https://data-stmo-rc.stage.mozaws.net/queries/new
2.  Observe the UI elemets

### Expected results:
There are no display issues 

### Actual results:
There is an element having "zmdi zmdi-minus-circle" class that is displayed next to the execute button

### Notes
Verified in FF66 win7x64 Issue can be reproduced in STMO-RC
Please view this screencast: 
![image](https://user-images.githubusercontent.com/15685441/58633581-8e70d800-82f1-11e9-926c-792e878e17da.png)

**Comment by emtwo** [comment]
This UI element seems to have something to do with the data source validator (https://github.com/mozilla/redash-stmo/blob/master/redash_stmo/data_sources/validator/bundle/datasource_validator.js)

Makes sense that it's showing up now since @washort just added the fix for extension installation.

@washort do you have an idea of what might be happening there?

**Comment by washort** [comment]
This was added in https://github.com/mozilla/redash-stmo/pull/27 - the intent is to show syntax checking for Postgres and BigQuery queries. I see that it's not working on RC, presumably because the UI elements it modifies were changed upstream. I recommend we drop this feature from the current release and try again next time -- it clearly needs both styling and behavior fixed.

**Comment by jezdez** [comment]
The UI element isn't show anymore, closing..

**Comment by madalincm** [comment]
Not reproducing anymore. Tried on Win7x64 and MacOS 10.14.1 FF68 on dev stage and prod.
